SECRET_KEY: <FILL IN>

model: davinci
num_generate: 10
max_tokens: 128
temperature: 0.0

# Optional lists for loops
models:
  - ada
  - babbage
  - curie
  - davinci

temperatures:
  - 0.7
  - 1.0
  - 1.2
